from pathlib import Path

MODEL_PROVIDER = "deepseek"

GEMINI_CHAT_MODEL = "gemini-2.0-flash"
GEMINI_EMBEDDING_MODEL = "models/embedding-001"

DEEPSEEK_CHAT_MODEL = "deepseek-chat"
DEEPSEEK_BASE_URL = "https://api.deepseek.com"

FASTEMBED_MODEL = "BAAI/bge-small-en-v1.5"

QDRANT_COLLECTION_PREFIX = "qdrant_db"
TITLE_COLLECTION_NAME = f"{QDRANT_COLLECTION_PREFIX}_title"
BODY_COLLECTION_NAME = f"{QDRANT_COLLECTION_PREFIX}_body"

MAX_REWRITE_ATTEMPTS = 2
BODY_RETRIEVAL_K = 8
TITLE_RETRIEVAL_K = 3
RERANK_TOP_K = 5
MAX_BATCH_URLS = 20
INGEST_CHUNK_SIZE = 700
INGEST_CHUNK_OVERLAP = 120

RETRIEVAL_MIN_DOCS = 3
RETRIEVAL_MIN_SCORE = 0.22
RETRIEVAL_MIN_QUERY_COVERAGE = 0.18
RETRIEVAL_EXPANSION_QUERIES = 3

CHAT_SESSIONS_FILE = Path("chat_sessions.json")

DEFAULT_MODEL_TEMPERATURE = 0.2
DEFAULT_MODEL_STREAMING = True
DEFAULT_MODEL_MAX_TOKENS = 1500


def get_provider_label() -> str:
    return "Gemini" if MODEL_PROVIDER == "gemini" else "DeepSeek"
